# Generated by Django 5.2.5 on 2025-08-16 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la sucursal', max_length=100, verbose_name='Nombre de la sucursal')),
                ('empresa', models.ForeignKey(help_text='Seleccione la empresa a la que pertenece esta sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sucursales', to='empresas.empresamodel', verbose_name='Empresa')),
                ('user_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL)),
                ('user_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
            },
        ),
    ]
