# Generated by Django 5.2.5 on 2025-08-16 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
        ('puestos', '0001_initial'),
        ('salarios', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='puestos.puestosmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='salario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salarios.salariomodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursalmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
