# Generated by Django 5.2.5 on 2025-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
