# Generated by Django 5.2.5 on 2025-08-17 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre del agrupador de incidencias', max_length=100)),
                ('user_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL)),
                ('user_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencias',
                'db_table': 'grupo_incidencias',
            },
        ),
        migrations.CreateModel(
            name='IncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre breve de la incidencia', max_length=100, verbose_name='Nombre de la Incidencia')),
                ('prompt', models.TextField(help_text='Descripción detallada de la incidencia', verbose_name='Descripción de la Incidencia')),
                ('user_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL)),
                ('user_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(help_text='Tipo de incidencia a la que pertenece', on_delete=django.db.models.deletion.PROTECT, to='incidencias.tipoincidenciamodel', verbose_name='Tipo de Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
            },
        ),
    ]
