# Generated by Django 5.2.5 on 2025-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_bitacoramodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoramodel',
            name='fecha_incidencia',
            field=models.DateTimeField(help_text='Fecha en que se registró la incidencia', verbose_name='Fecha de Incidencia'),
        ),
    ]
