# Generated by Django 5.2.5 on 2025-08-17 06:03

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_alter_bitacoramodel_fecha_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoramodel',
            name='monto',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='MXN', help_text='Monto asociado a la incidencia', max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
