# Generated by Django 5.2.5 on 2025-08-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_alter_bitacoramodel_monto'),
        ('salarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoramodel',
            name='cubre_puesto',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si la incidencia cubre el puesto del usuario', null=True, verbose_name='Cubre Puesto'),
        ),
        migrations.AddField(
            model_name='bitacoramodel',
            name='salario',
            field=models.ForeignKey(blank=True, help_text='Salario diferente al habitual si es que aplica', null=True, on_delete=django.db.models.deletion.PROTECT, to='salarios.salariomodel', verbose_name='Puesto/Salario objetivo'),
        ),
    ]
