# Generated by Django 5.2.5 on 2025-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0006_bitacoramodel_cubre_puesto_bitacoramodel_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoramodel',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], db_index=True, default='en_proceso', help_text='Estado actual de la incidencia', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bitacoramodel',
            name='fecha_incidencia',
            field=models.DateField(db_index=True, help_text='Fecha en que se registró la incidencia', verbose_name='Fecha de Incidencia'),
        ),
    ]
