# Generated by Django 5.2.5 on 2025-08-21 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0007_alter_bitacoramodel_estado_and_more'),
        ('salarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bitacoramodel',
            index=models.Index(fields=['estado', '-fecha_incidencia'], name='idx_estado_fecha'),
        ),
    ]
