# Generated by Django 5.2.5 on 2025-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre del turno', max_length=50, verbose_name='Turno')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno', verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno', verbose_name='Hora de fin')),
                ('user_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL)),
                ('user_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='PlantillaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('dia', models.DateField(help_text='Día de trabajo', verbose_name='Día')),
                ('empleados', models.ManyToManyField(help_text='Empleados asignados', related_name='plantillas', to=settings.AUTH_USER_MODEL, verbose_name='Empleados')),
                ('sucursal', models.ForeignKey(help_text='Sucursal donde se trabaja', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_plantillas', to='sucursales.sucursalmodel', verbose_name='Sucursal')),
                ('user_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creacion', to=settings.AUTH_USER_MODEL)),
                ('user_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificacion', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(help_text='Turno de trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='horarios.turnosmodel', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'db_table': 'plantillas',
            },
        ),
    ]
