# Generated by Django 5.2.5 on 2025-08-21 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillamodel',
            name='empleados',
            field=models.ManyToManyField(db_index=True, help_text='Empleados asignados', related_name='plantillas', to=settings.AUTH_USER_MODEL, verbose_name='Empleados'),
        ),
    ]
